### ISSUE TITLE
COUNT based triggers fail with an unknown column error

### ISSUE THREAD

**Issue by fitzoh** [kvrhdn/terraform-provider-honeycombio#17]
When adding a trigger with a query that has a calculation of `op = "COUNT"` and no column it fails with the following error: `400 Bad Request: unknown column `

**Comment by kvrhdn** [comment]
Ah, the issue seems to be that we set an empty string in `column`, while this field is a `*string` and should be set to `nil`.

Here we assign this field: https://github.com/kvrhdn/terraform-provider-honeycombio/blob/main/honeycombio/data_source_query.go#L122
The Terraform SDK will return the default value for properties that are not set, in this case that's `""`.

This `column` field is set to `json:omitempty`: https://github.com/kvrhdn/go-honeycombio/blob/main/query_spec.go#L28
But since it's a pointer, `""` is considered a non-empty value.

I should be able fix this later today. Thanks for the testcase!
