### ISSUE TITLE
Minor: suppress diff when trigger recipient id is specified

### ISSUE THREAD

**Issue by fitzoh** [kvrhdn/terraform-provider-honeycombio#26]
provider version = 0.0.7

Disclaimer: this might be a bad idea.

I've got the following terraform configuration that applies successfully and works as expected:
```terraform


data "honeycombio_trigger_recipient" "slack" {
  dataset = "my-very-special-datset"
  type    = "slack"
  target  = "#alerts"
}


resource "honeycombio_trigger" "trigger" {
  
 //query omitted

  recipient {
    id     = data.honeycombio_trigger_recipient.slack.id
  }
}
```

However, I receive the following when I run a plan/apply

```    
 ~ recipient {
            id     = "some-id"
          - target = "#alerts" -> null
          - type   = "slack" -> null
        }
```

It would be nice if that diff could be suppressed without duplicating the recipient target and type.

**Comment by kvrhdn** [comment]
Ah good call. This can be fixed by setting `target` and `type` as computed fields. In this case Terraform also accepts changes from coming from API.

Looking [at the schema](https://github.com/kvrhdn/terraform-provider-honeycombio/blob/main/honeycombio/resource_trigger.go#L77), `id` is computed but the other two fields of a recipient aren't.

**Comment by kvrhdn** [comment]
Didn't intend to push to main straight away, but this is fixed now 😅
